GENRE_ARTIST_MAP = {
    "Desi Hip-Hop": [
        {"name": "Divine", "image_slug": "divine", "style_description": "Street Rap • Desi Hip-Hop"},
        {"name": "Kr$na", "image_slug": "krsna", "style_description": "Lyrical Rap • Desi Hip-Hop"},
        {"name": "Emiway Bantai", "image_slug": "emiway_bantai", "style_description": "Independent • Desi Hip-Hop"},
        {"name": "MC Stan", "image_slug": "mc_stan", "style_description": "Trap • Desi Hip-Hop"},
        {"name": "Ikka", "image_slug": "ikka", "style_description": "Commercial • Desi Rap"},
        {"name": "Hanumankind", "image_slug": "hanumankind", "style_description": "Experimental • Desi Hip-Hop"},
    ],
    "Bollywood": [
        {"name": "Arijit Singh", "image_slug": "arijit_singh", "style_description": "Romantic • Playback"},
        {"name": "Shreya Ghoshal", "image_slug": "shreya_ghoshal", "style_description": "Melodic • Classical"},
        {"name": "Neha Kakkar", "image_slug": "neha_kakkar", "style_description": "Dance • Pop"},
        {"name": "Jubin Nautiyal", "image_slug": "jubin_nautiyal", "style_description": "Ballad • Playback"},
        {"name": "Armaan Malik", "image_slug": "armaan_malik", "style_description": "Romantic • Pop"},
        {"name": "Badshah", "image_slug": "badshah", "style_description": "Rap • Bollywood Pop"},
    ],
    "Pop": [
        {"name": "Darshan Raval", "image_slug": "darshan_raval", "style_description": "Romantic • Pop"},
        {"name": "Anuv Jain", "image_slug": "anuv_jain", "style_description": "Indie Pop • Acoustic"},
        {"name": "Jasleen Royal", "image_slug": "jasleen_royal", "style_description": "Indie Pop • Folk"},
        {"name": "Lisa Mishra", "image_slug": "lisa_mishra", "style_description": "Indie Pop • R&B"},
        {"name": "Prateek Kuhad", "image_slug": "prateek_kuhad", "style_description": "Singer-Songwriter • Indie Pop"},
        {"name": "Asees Kaur", "image_slug": "asees_kaur", "style_description": "Bollywood • Pop"},
    ],
    "Rock": [
        {"name": "Parvaaz", "image_slug": "parvaaz", "style_description": "Psychedelic Rock • Fusion"},
        {"name": "Peter Cat Recording Co.", "image_slug": "peter_cat_recording_co", "style_description": "Indie Rock • Jazz Fusion"},
        {"name": "Bloodywood", "image_slug": "bloodywood", "style_description": "Folk Metal • Nu Metal"},
        {"name": "The Local Train", "image_slug": "the_local_train", "style_description": "Alternative Rock • Hindi Rock"},
        {"name": "Swarathma", "image_slug": "swarathma", "style_description": "Folk Rock • Fusion"},
        {"name": "Agnee", "image_slug": "agnee", "style_description": "Rock • Folk Fusion"},
    ],
    "Electronic": [
        {"name": "Nucleya", "image_slug": "nucleya", "style_description": "Bass Music • EDM"},
        {"name": "Ritviz", "image_slug": "ritviz", "style_description": "Electronic • Pop"},
        {"name": "Lost Stories", "image_slug": "lost_stories", "style_description": "Progressive House • EDM"},
        {"name": "Zaeden", "image_slug": "zaeden", "style_description": "Pop • EDM"},
        {"name": "OX7GEN", "image_slug": "ox7gen", "style_description": "Drum & Bass • Electronic"},
        {"name": "Anish Sood", "image_slug": "anish_sood", "style_description": "House • Electronic"},
    ],
    "Indie": [
        {"name": "Prateek Kuhad", "image_slug": "prateek_kuhad", "style_description": "Indie Folk • Singer-Songwriter"},
        {"name": "Ankur Tewari", "image_slug": "ankur_tewari", "style_description": "Indie Rock • Acoustic"},
        {"name": "When Chai Met Toast", "image_slug": "when_chai_met_toast", "style_description": "Indie Pop • Folk"},
        {"name": "Parekh & Singh", "image_slug": "parekh_singh", "style_description": "Dream Pop • Indie"},
        {"name": "The Yellow Diary", "image_slug": "the_yellow_diary", "style_description": "Alternative Rock • Indie"},
        {"name": "Ankur & The Ghalat Family", "image_slug": "ankur_ghalat_family", "style_description": "Indie Rock • Folk"},
    ],
}
